#!/bin/bash

build() {
	cd dwm-6.0

	cp ../config.h config.h

    patch -Np1 -i ../01-tilegap.diff || exit 1
    patch -Np1 -i ../02-centredfloating.diff || exit 1
    patch -Np1 -i ../03-systray.diff || exit 1
    patch -Np1 -i ../04-pertag.diff || exit 1
    patch -Np1 -i ../05-attachabove.diff || exit 1
    patch -Np1 -i ../06-focusadjacenttag3.diff || exit 1
    patch -Np1 -i ../07-pushnomaster.diff || exit 1
    patch -Np1 -i ../08-save_floats.diff || exit 1

	make && sudo make PREFIX=/usr install
	#make PREFIX=/usr DESTDIR=$PKG install

    #install -m644 -D $SRC/dwm.desktop $PKG/usr/share/xsessions/dwm.desktop
}

download_dwm() {
	[ ! -f dwm-6.0.tar.gz ] && wget -c http://dl.suckless.org/dwm/dwm-6.0.tar.gz
}

extract() {
	[ -f dwm-6.0.tar.gz ] && tar xvf dwm-6.0.tar.gz || download_dwm
}

download_dwm
extract
build
cd .. && rm -Rfv dwm-6.0
